// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindTurbine.DataAccess.Context;

#nullable disable

namespace WindTurbine.DataAccess.Migrations
{
    [DbContext(typeof(WindTurbineDbContext))]
    [Migration("20251124154359_AddDetailSensors2")]
    partial class AddDetailSensors2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WindTurbine.Entities.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TurbineId")
                        .HasColumnType("int");

                    b.HasKey("AlertId");

                    b.HasIndex("TurbineId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("WindTurbine.Entities.GeneratedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeneratedReports");
                });

            modelBuilder.Entity("WindTurbine.Entities.Turbine", b =>
                {
                    b.Property<int>("TurbineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurbineId"));

                    b.Property<double>("BladeVibration")
                        .HasColumnType("float");

                    b.Property<double>("CurrentPower")
                        .HasColumnType("float");

                    b.Property<double>("CurrentWindSpeed")
                        .HasColumnType("float");

                    b.Property<double>("GearboxOilTemp")
                        .HasColumnType("float");

                    b.Property<double>("GearboxVibration")
                        .HasColumnType("float");

                    b.Property<double>("GeneratorRPM")
                        .HasColumnType("float");

                    b.Property<double>("GeneratorTemp")
                        .HasColumnType("float");

                    b.Property<double>("HubTemperature")
                        .HasColumnType("float");

                    b.Property<string>("LastStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("MainBearingTemp")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PitchAngle")
                        .HasColumnType("float");

                    b.Property<double>("TransformerTemp")
                        .HasColumnType("float");

                    b.Property<int>("WindFarmId")
                        .HasColumnType("int");

                    b.HasKey("TurbineId");

                    b.HasIndex("WindFarmId");

                    b.ToTable("Turbines");
                });

            modelBuilder.Entity("WindTurbine.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WindTurbine.Entities.WindFarm", b =>
                {
                    b.Property<int>("WindFarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WindFarmId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WindFarmId");

                    b.ToTable("WindFarms");
                });

            modelBuilder.Entity("WindTurbine.Entities.Alert", b =>
                {
                    b.HasOne("WindTurbine.Entities.Turbine", "Turbine")
                        .WithMany("Alerts")
                        .HasForeignKey("TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("WindTurbine.Entities.Turbine", b =>
                {
                    b.HasOne("WindTurbine.Entities.WindFarm", "WindFarm")
                        .WithMany("Turbines")
                        .HasForeignKey("WindFarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WindFarm");
                });

            modelBuilder.Entity("WindTurbine.Entities.Turbine", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("WindTurbine.Entities.WindFarm", b =>
                {
                    b.Navigation("Turbines");
                });
#pragma warning restore 612, 618
        }
    }
}
